const trainData = [{
    source: 'bedford',
    target: 'subway',
    time: 1,
    volume: 280
  }, {
    source: 'bedford',
    target: 'subway',
    time: 2,
    volume: 280
  }, {
    source: 'bedford',
    target: 'subway',
    time: 3,
    volume: 280
  }, {
    source: 'bedford',
    target: 'subway',
    time: 4,
    volume: 280
  }, {
    source: 'bedford',
    target: 'subway',
    time: 5,
    volume: 975
  }, {
    source: 'bedford',
    target: 'subway',
    time: 6,
    volume: 975
  }, {
    source: 'bedford',
    target: 'subway',
    time: 7,
    volume: 975
  }, {
    source: 'bedford',
    target: 'subway',
    time: 8,
    volume: 975
  }, {
    source: 'bedford',
    target: 'subway',
    time: 9,
    volume: 3900
  }, {
    source: 'bedford',
    target: 'subway',
    time: 10,
    volume: 3900
  }, {
    source: 'bedford',
    target: 'subway',
    time: 11,
    volume: 3900
  }, {
    source: 'bedford',
    target: 'subway',
    time: 12,
    volume: 3900
  }, {
    source: 'bedford',
    target: 'subway',
    time: 13,
    volume: 2000
  }, {
    source: 'bedford',
    target: 'subway',
    time: 14,
    volume: 2000
  }, {
    source: 'bedford',
    target: 'subway',
    time: 15,
    volume: 2000
  }, {
    source: 'bedford',
    target: 'subway',
    time: 16,
    volume: 2000
  }, {
    source: 'bedford',
    target: 'subway',
    time: 17,
    volume: 2300
  }, {
    source: 'bedford',
    target: 'subway',
    time: 18,
    volume: 2300
  }, {
    source: 'bedford',
    target: 'subway',
    time: 19,
    volume: 2300
  }, {
    source: 'bedford',
    target: 'subway',
    time: 20,
    volume: 2300
  }, {
    source: 'bedford',
    target: 'subway',
    time: 21,
    volume: 800
  }, {
    source: 'bedford',
    target: 'subway',
    time: 22,
    volume: 800
  }, {
    source: 'bedford',
    target: 'subway',
    time: 23,
    volume: 800
  }, {
    source: 'bedford',
    target: 'subway',
    time: 24,
    volume: 800
  }, {
    source: 'subway',
    target: 'bedford',
    time: 1,
    volume: 75
  }, {
    source: 'subway',
    target: 'bedford',
    time: 2,
    volume: 75
  }, {
    source: 'subway',
    target: 'bedford',
    time: 3,
    volume: 75
  }, {
    source: 'subway',
    target: 'bedford',
    time: 4,
    volume: 75
  }, {
    source: 'subway',
    target: 'bedford',
    time: 5,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 6,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 7,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 8,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 9,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 10,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 11,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 12,
    volume: 350
  }, {
    source: 'subway',
    target: 'bedford',
    time: 13,
    volume: 700
  }, {
    source: 'subway',
    target: 'bedford',
    time: 14,
    volume: 700
  }, {
    source: 'subway',
    target: 'bedford',
    time: 15,
    volume: 700
  }, {
    source: 'subway',
    target: 'bedford',
    time: 16,
    volume: 700
  }, {
    source: 'subway',
    target: 'bedford',
    time: 17,
    volume: 2200
  }, {
    source: 'subway',
    target: 'bedford',
    time: 18,
    volume: 2200
  }, {
    source: 'subway',
    target: 'bedford',
    time: 19,
    volume: 2200
  }, {
    source: 'subway',
    target: 'bedford',
    time: 20,
    volume: 2200
  }, {
    source: 'subway',
    target: 'bedford',
    time: 21,
    volume: 1000
  }, {
    source: 'subway',
    target: 'bedford',
    time: 22,
    volume: 1000
  }, {
    source: 'subway',
    target: 'bedford',
    time: 23,
    volume: 1000
  }, {
    source: 'subway',
    target: 'bedford',
    time: 24,
    volume: 1000
  },
  {
    source: 'citi-N6',
    target: 'bedford',
    time: 1,
    volume: 0
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 2,
    volume: 1
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 3,
    volume: 0
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 4,
    volume: 0
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 5,
    volume: 2
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 6,
    volume: 7
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 7,
    volume: 16
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 8,
    volume: 16
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 9,
    volume: 11
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 10,
    volume: 9
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 11,
    volume: 6
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 12,
    volume: 3
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 13,
    volume: 11
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 14,
    volume: 6
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 15,
    volume: 8
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 16,
    volume: 5
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 17,
    volume: 5
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 18,
    volume: 8
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 19,
    volume: 9
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 20,
    volume: 8
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 21,
    volume: 5
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 22,
    volume: 1
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 23,
    volume: 0
  }, {
    source: 'citi-N6',
    target: 'bedford',
    time: 24,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 1,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 2,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 3,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 4,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 5,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 6,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 7,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 8,
    volume: 10
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 9,
    volume: 9
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 10,
    volume: 10
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 11,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 12,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 13,
    volume: 13
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 14,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 15,
    volume: 11
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 16,
    volume: 10
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 17,
    volume: 15
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 18,
    volume: 11
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 19,
    volume: 10
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 20,
    volume: 7
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 21,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 22,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 23,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N6',
    time: 24,
    volume: 0
  },
  {
    source: 'citi-N8',
    target: 'bedford',
    time: 1,
    volume: 0
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 2,
    volume: 0
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 3,
    volume: 0
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 4,
    volume: 0
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 5,
    volume: 1
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 6,
    volume: 5
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 7,
    volume: 18
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 8,
    volume: 20
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 9,
    volume: 13
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 10,
    volume: 4
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 11,
    volume: 2
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 12,
    volume: 1
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 13,
    volume: 5
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 14,
    volume: 8
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 15,
    volume: 6
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 16,
    volume: 6
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 17,
    volume: 5
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 18,
    volume: 7
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 19,
    volume: 5
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 20,
    volume: 4
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 21,
    volume: 3
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 22,
    volume: 2
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 23,
    volume: 0
  }, {
    source: 'citi-N8',
    target: 'bedford',
    time: 24,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 1,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 2,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 3,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 4,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 5,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 6,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 7,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 8,
    volume: 7
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 9,
    volume: 15
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 10,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 11,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 12,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 13,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 14,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 15,
    volume: 13
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 16,
    volume: 9
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 17,
    volume: 16
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 18,
    volume: 11
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 19,
    volume: 6
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 20,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 21,
    volume: 3
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 22,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 23,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-N8',
    time: 24,
    volume: 0
  },
  {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 1,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 2,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 3,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 4,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 5,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 6,
    volume: 1
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 7,
    volume: 3
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 8,
    volume: 2
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 9,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 10,
    volume: 1
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 11,
    volume: 4
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 12,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 13,
    volume: 1
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 14,
    volume: 6
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 15,
    volume: 2
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 16,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 17,
    volume: 2
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 18,
    volume: 8
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 19,
    volume: 4
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 20,
    volume: 7
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 21,
    volume: 6
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 22,
    volume: 0
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 23,
    volume: 1
  }, {
    source: 'citi-Roebling',
    target: 'bedford',
    time: 24,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 1,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 2,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 3,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 4,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 5,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 6,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 7,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 8,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 9,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 10,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 11,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 12,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 13,
    volume: 3
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 14,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 15,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 16,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 17,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 18,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 19,
    volume: 6
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 20,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 21,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 22,
    volume: 7
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 23,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Roebling',
    time: 24,
    volume: 1
  },
  {
    source: 'citi-Metro',
    target: 'bedford',
    time: 1,
    volume: 0
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 2,
    volume: 0
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 3,
    volume: 0
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 4,
    volume: 1
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 5,
    volume: 2
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 6,
    volume: 9
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 7,
    volume: 6
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 8,
    volume: 9
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 9,
    volume: 9
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 10,
    volume: 7
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 11,
    volume: 5
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 12,
    volume: 6
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 13,
    volume: 8
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 14,
    volume: 8
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 15,
    volume: 10
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 16,
    volume: 6
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 17,
    volume: 7
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 18,
    volume: 14
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 19,
    volume: 18
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 20,
    volume: 13
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 21,
    volume: 6
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 22,
    volume: 3
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 23,
    volume: 3
  }, {
    source: 'citi-Metro',
    target: 'bedford',
    time: 24,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 1,
    volume: 3
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 2,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 3,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 4,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 5,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 6,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 7,
    volume: 6
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 8,
    volume: 10
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 9,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 10,
    volume: 19
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 11,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 12,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 13,
    volume: 13
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 14,
    volume: 11
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 15,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 16,
    volume: 6
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 17,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 18,
    volume: 9
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 19,
    volume: 14
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 20,
    volume: 16
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 21,
    volume: 14
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 22,
    volume: 3
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 23,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-Metro',
    time: 24,
    volume: 1
  },
  {
    source: 'citi-berry',
    target: 'bedford',
    time: 1,
    volume: 0
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 2,
    volume: 0
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 3,
    volume: 0
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 4,
    volume: 0
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 5,
    volume: 0
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 6,
    volume: 0
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 7,
    volume: 5
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 8,
    volume: 20
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 9,
    volume: 13
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 10,
    volume: 6
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 11,
    volume: 1
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 12,
    volume: 7
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 13,
    volume: 2
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 14,
    volume: 3
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 15,
    volume: 9
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 16,
    volume: 2
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 17,
    volume: 7
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 18,
    volume: 4
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 19,
    volume: 10
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 20,
    volume: 1
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 21,
    volume: 2
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 22,
    volume: 3
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 23,
    volume: 1
  }, {
    source: 'citi-berry',
    target: 'bedford',
    time: 24,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 1,
    volume: 1
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 2,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 3,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 4,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 5,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 6,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 7,
    volume: 0
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 8,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 9,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 10,
    volume: 5
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 11,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 12,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 13,
    volume: 6
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 14,
    volume: 6
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 15,
    volume: 4
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 16,
    volume: 7
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 17,
    volume: 9
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 18,
    volume: 12
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 19,
    volume: 9
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 20,
    volume: 8
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 21,
    volume: 3
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 22,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 23,
    volume: 2
  }, {
    source: 'bedford',
    target: 'citi-berry',
    time: 24,
    volume: 0
  }
];

const transport = [{
    type: 'citi-N6',
    cx: 340,
    cy: 0
  }, {
    type: 'subway',
    cx: -340,
    cy: 0
  }, {
    type: 'citi-N8',
    cx: 0,
    cy: -340
  },
  {
    type: 'citi-berry',
    cx: 0,
    cy: 340
  },
  {
    type: 'citi-Metro',
    cx: -250,
    cy: -250
  },
  {
    type: 'citi-Roebling',
    cx: 250,
    cy: -250
  }
];

const transportCoords = {
  'citi-N6': [160, 0],
  subway: [200, 200],
  'citi-N8': [300, 300]
};
