let trainData =  [
  {
      source: 'bedford',
      target: 'subway',
      time: 1,
      volume: 280
  }, {
      source: 'bedford',
      target: 'subway',
      time: 2,
      volume: 280
  }, {
      source: 'bedford',
      target: 'subway',
      time: 3,
      volume: 280
  }, {
      source: 'bedford',
      target: 'subway',
      time: 4,
      volume: 280
  }, {
      source: 'bedford',
      target: 'subway',
      time: 5,
      volume: 975
  }, {
      source: 'bedford',
      target: 'subway',
      time: 6,
      volume: 975
  }, {
      source: 'bedford',
      target: 'subway',
      time: 7,
      volume: 975
  }, {
      source: 'bedford',
      target: 'subway',
      time: 8,
      volume: 975
  }, {
      source: 'bedford',
      target: 'subway',
      time: 9,
      volume: 3900
  }, {
      source: 'bedford',
      target: 'subway',
      time: 10,
      volume: 3900
  }, {
      source: 'bedford',
      target: 'subway',
      time: 11,
      volume: 3900
  }, {
      source: 'bedford',
      target: 'subway',
      time: 12,
      volume: 3900
  }, {
      source: 'bedford',
      target: 'subway',
      time: 13,
      volume: 2000
  }, {
      source: 'bedford',
      target: 'subway',
      time: 14,
      volume: 2000
  }, {
      source: 'bedford',
      target: 'subway',
      time: 15,
      volume: 2000
  }, {
      source: 'bedford',
      target: 'subway',
      time: 16,
      volume: 2000
  }, {
      source: 'bedford',
      target: 'subway',
      time: 17,
      volume: 2300
  }, {
      source: 'bedford',
      target: 'subway',
      time: 18,
      volume: 2300
  }, {
      source: 'bedford',
      target: 'subway',
      time: 19,
      volume: 2300
  }, {
      source: 'bedford',
      target: 'subway',
      time: 20,
      volume: 2300
  }, {
      source: 'bedford',
      target: 'subway',
      time: 21,
      volume: 800
  }, {
      source: 'bedford',
      target: 'subway',
      time: 22,
      volume: 800
  }, {
      source: 'bedford',
      target: 'subway',
      time: 23,
      volume: 800
  }, {
      source: 'bedford',
      target: 'subway',
      time: 24,
      volume: 800
  }, {
      source: 'subway',
      target: 'bedford',
      time: 1,
      volume: 75
  }, {
      source: 'subway',
      target: 'bedford',
      time: 2,
      volume: 75
  }, {
      source: 'subway',
      target: 'bedford',
      time: 3,
      volume: 75
  }, {
      source: 'subway',
      target: 'bedford',
      time: 4,
      volume: 75
  }, {
      source: 'subway',
      target: 'bedford',
      time: 5,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 6,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 7,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 8,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 9,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 10,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 11,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 12,
      volume: 350
  }, {
      source: 'subway',
      target: 'bedford',
      time: 13,
      volume: 700
  }, {
      source: 'subway',
      target: 'bedford',
      time: 14,
      volume: 700
  }, {
      source: 'subway',
      target: 'bedford',
      time: 15,
      volume: 700
  }, {
      source: 'subway',
      target: 'bedford',
      time: 16,
      volume: 700
  }, {
      source: 'subway',
      target: 'bedford',
      time: 17,
      volume: 2200
  }, {
      source: 'subway',
      target: 'bedford',
      time: 18,
      volume: 2200
  }, {
      source: 'subway',
      target: 'bedford',
      time: 19,
      volume: 2200
  }, {
      source: 'subway',
      target: 'bedford',
      time: 20,
      volume: 2200
  }, {
      source: 'subway',
      target: 'bedford',
      time: 21,
      volume: 1000
  }, {
      source: 'subway',
      target: 'bedford',
      time: 22,
      volume: 1000
  }, {
      source: 'subway',
      target: 'bedford',
      time: 23,
      volume: 1000
  }, {
      source: 'subway',
      target: 'bedford',
      time: 24,
      volume: 1000
  }
];
